# Generated by Django 5.1.1 on 2024-11-20 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='admin',
            field=models.ForeignKey(default=1, limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.PROTECT, related_name='received_payment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='dealer_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_payment_requests', to='accounts.dealer'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='sender_type',
            field=models.CharField(choices=[('DEALER', 'Dealer'), ('SERVICE_PROVIDER', 'Service Provider')], default='DEALER', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='service_provider_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_payment_requests', to='accounts.serviceprovider'),
        ),
    ]
