# Generated by Django 5.1.1 on 2024-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paymentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='booking_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
