# Generated by Django 5.1.1 on 2024-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_servicerequest_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='booking_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
