# Generated by Django 5.1.1 on 2024-12-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_servicerequest_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_management',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images/'),
        ),
    ]
